### ISSUE TITLE
Alte Tekton API Version

### ISSUE THREAD

**Issue by schlapzz** [puzzle/amm-techlab#58]
Die Tekont resourcen im AMM Techlab sind noch auf der API Version `tekton.dev/v1alpha1` 
Neuste Version ist `tekton.dev/v1beta1` (Seit Juli 2020, auch alle Beispiele aus dem Tekton repository verwenden mittlerweile die neuste API Version)
Anpassen? Ja/Nein?

Changelog:
https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md

**Comment by schlapzz** [comment]
Ausserdem wird empfohlen anstelle von PipelineResources die Tekton Catalog Tasks zu verwenden.
https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md#pipelineresources-and-catalog-tasks
Bei Bedarf kann ich das auch noch anpassen

**Comment by chrira** [comment]
Anpassungen sind gemacht: 48d6483052066c79ced0888c4d8071b20bda8cf3
